/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameProgressDto } from '../../models/game-progress-dto';

export interface StartNewGameSession$Params {
  userId: number;
  gameId: number;
}

export function startNewGameSession(http: HttpClient, rootUrl: string, params: StartNewGameSession$Params, context?: HttpContext): Observable<StrictHttpResponse<GameProgressDto>> {
  const rb = new RequestBuilder(rootUrl, startNewGameSession.PATH, 'post');
  if (params) {
    rb.query('userId', params.userId, {});
    rb.query('gameId', params.gameId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GameProgressDto>;
    })
  );
}

startNewGameSession.PATH = '/gametracker/v1/progress/start';
