/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameProgressDto } from '../../models/game-progress-dto';

export interface UpdateBestScore$Params {
  progressId: number;
  newScore: number;
}

export function updateBestScore(http: HttpClient, rootUrl: string, params: UpdateBestScore$Params, context?: HttpContext): Observable<StrictHttpResponse<GameProgressDto>> {
  const rb = new RequestBuilder(rootUrl, updateBestScore.PATH, 'put');
  if (params) {
    rb.path('progressId', params.progressId, {});
    rb.query('newScore', params.newScore, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GameProgressDto>;
    })
  );
}

updateBestScore.PATH = '/gametracker/v1/progress/{progressId}/score';
