/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FriendshipDto } from '../../models/friendship-dto';

export interface CancelFriendship$Params {
  userId: number;
  friendId: number;
}

export function cancelFriendship(http: HttpClient, rootUrl: string, params: CancelFriendship$Params, context?: HttpContext): Observable<StrictHttpResponse<FriendshipDto>> {
  const rb = new RequestBuilder(rootUrl, cancelFriendship.PATH, 'put');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.path('friendId', params.friendId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FriendshipDto>;
    })
  );
}

cancelFriendship.PATH = '/gametracker/v1/friendships/cancel/{userId}/friend/{friendId}';
