/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserDto } from '../../models/user-dto';

export interface GetMutualFriends$Params {
  user1Id: number;
  user2Id: number;
}

export function getMutualFriends(http: HttpClient, rootUrl: string, params: GetMutualFriends$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<UserDto>>> {
  const rb = new RequestBuilder(rootUrl, getMutualFriends.PATH, 'get');
  if (params) {
    rb.path('user1Id', params.user1Id, {});
    rb.path('user2Id', params.user2Id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<UserDto>>;
    })
  );
}

getMutualFriends.PATH = '/gametracker/v1/friendships/mutual/{user1Id}/user/{user2Id}';
