/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface GetRelationshipStatus$Params {
  user1Id: number;
  user2Id: number;
}

export function getRelationshipStatus(http: HttpClient, rootUrl: string, params: GetRelationshipStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<'PENDING' | 'ACCEPTED' | 'DECLINED'>> {
  const rb = new RequestBuilder(rootUrl, getRelationshipStatus.PATH, 'get');
  if (params) {
    rb.path('user1Id', params.user1Id, {});
    rb.path('user2Id', params.user2Id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<'PENDING' | 'ACCEPTED' | 'DECLINED'>;
    })
  );
}

getRelationshipStatus.PATH = '/gametracker/v1/friendships/status/{user1Id}/user/{user2Id}';
