/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FriendshipDto } from '../../models/friendship-dto';

export interface SearchFriendshipsByUser$Params {
  username: string;
}

export function searchFriendshipsByUser(http: HttpClient, rootUrl: string, params: SearchFriendshipsByUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FriendshipDto>>> {
  const rb = new RequestBuilder(rootUrl, searchFriendshipsByUser.PATH, 'get');
  if (params) {
    rb.path('username', params.username, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FriendshipDto>>;
    })
  );
}

searchFriendshipsByUser.PATH = '/gametracker/v1/friendships/admin/search/{username}';
