/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageReportDto } from '../../models/page-report-dto';

export interface GetUnresolvedReports$Params {
  pageable: Pageable;
}

export function getUnresolvedReports(http: HttpClient, rootUrl: string, params: GetUnresolvedReports$Params, context?: HttpContext): Observable<StrictHttpResponse<PageReportDto>> {
  const rb = new RequestBuilder(rootUrl, getUnresolvedReports.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageReportDto>;
    })
  );
}

getUnresolvedReports.PATH = '/gametracker/v1/report/unresolved';
