/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Game } from '../../models/game';

export interface GetGameByUrl$Params {
  url: string;
}

export function getGameByUrl(http: HttpClient, rootUrl: string, params: GetGameByUrl$Params, context?: HttpContext): Observable<StrictHttpResponse<Game>> {
  const rb = new RequestBuilder(rootUrl, getGameByUrl.PATH, 'get');
  if (params) {
    rb.path('url', params.url, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Game>;
    })
  );
}

getGameByUrl.PATH = '/gametracker/v1/game/url/{url}';
