/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Game } from '../../models/game';

export interface GetHighlyRatedGames$Params {
  minRating: number;
}

export function getHighlyRatedGames(http: HttpClient, rootUrl: string, params: GetHighlyRatedGames$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Game>>> {
  const rb = new RequestBuilder(rootUrl, getHighlyRatedGames.PATH, 'get');
  if (params) {
    rb.query('minRating', params.minRating, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Game>>;
    })
  );
}

getHighlyRatedGames.PATH = '/gametracker/v1/game/rating';
