/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface SavePhoto$Params {

/**
 * Contexte définissant le type d'entité (avatar, achievement, etc.)
 */
  context: string;

/**
 * ID de l'entité à laquelle associer la photo
 */
  id: number;

/**
 * Titre ou nom de la photo
 */
  title: string;
      body?: {

/**
 * Fichier image à télécharger
 */
'file': Blob;
}
}

export function savePhoto(http: HttpClient, rootUrl: string, params: SavePhoto$Params, context?: HttpContext): Observable<StrictHttpResponse<{
}>> {
  const rb = new RequestBuilder(rootUrl, savePhoto.PATH, 'post');
  if (params) {
    rb.path('context', params.context, {});
    rb.path('id', params.id, {});
    rb.path('title', params.title, {});
    rb.body(params.body, 'multipart/form-data');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      }>;
    })
  );
}

savePhoto.PATH = '/gametracker/v1/photos/{id}/{title}/{context}';
