/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DailyGameSessionDto } from '../../models/daily-game-session-dto';

export interface CreateSession$Params {
      body: DailyGameSessionDto
}

export function createSession(http: HttpClient, rootUrl: string, params: CreateSession$Params, context?: HttpContext): Observable<StrictHttpResponse<DailyGameSessionDto>> {
  const rb = new RequestBuilder(rootUrl, createSession.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DailyGameSessionDto>;
    })
  );
}

createSession.PATH = '/gametracker/v1/sessions/create';
