/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DailyGameSessionDto } from '../../models/daily-game-session-dto';

export interface GetSessionByUserAndDate$Params {
  userId: number;
  date: string;
}

export function getSessionByUserAndDate(http: HttpClient, rootUrl: string, params: GetSessionByUserAndDate$Params, context?: HttpContext): Observable<StrictHttpResponse<DailyGameSessionDto>> {
  const rb = new RequestBuilder(rootUrl, getSessionByUserAndDate.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.path('date', params.date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DailyGameSessionDto>;
    })
  );
}

getSessionByUserAndDate.PATH = '/gametracker/v1/sessions/user/{userId}/date/{date}';
