/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AchievementDto } from '../../models/achievement-dto';

export interface GetAchievementById$Params {
  idAchievement: number;
}

export function getAchievementById(http: HttpClient, rootUrl: string, params: GetAchievementById$Params, context?: HttpContext): Observable<StrictHttpResponse<AchievementDto>> {
  const rb = new RequestBuilder(rootUrl, getAchievementById.PATH, 'get');
  if (params) {
    rb.path('idAchievement', params.idAchievement, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AchievementDto>;
    })
  );
}

getAchievementById.PATH = '/gametracker/v1/achievements/{idAchievement}';
