/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameLeaderboardDto } from '../../models/game-leaderboard-dto';

export interface GetTopRankedPlayersByGamePeriod$Params {
  gameId: number;
  period: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY' | 'ALL_TIME';
  limit: number;
}

export function getTopRankedPlayersByGamePeriod(http: HttpClient, rootUrl: string, params: GetTopRankedPlayersByGamePeriod$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GameLeaderboardDto>>> {
  const rb = new RequestBuilder(rootUrl, getTopRankedPlayersByGamePeriod.PATH, 'get');
  if (params) {
    rb.path('gameId', params.gameId, {});
    rb.path('period', params.period, {});
    rb.path('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GameLeaderboardDto>>;
    })
  );
}

getTopRankedPlayersByGamePeriod.PATH = '/gametracker/v1/leaderboard/game/{gameId}/period/{period}/limit/{limit}';
