/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameLeaderboardDto } from '../../models/game-leaderboard-dto';

export interface GetLeaderBoardByGameUserPeriod$Params {
  gameId: number;
  userId: number;
  period: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY' | 'ALL_TIME';
}

export function getLeaderBoardByGameUserPeriod(http: HttpClient, rootUrl: string, params: GetLeaderBoardByGameUserPeriod$Params, context?: HttpContext): Observable<StrictHttpResponse<GameLeaderboardDto>> {
  const rb = new RequestBuilder(rootUrl, getLeaderBoardByGameUserPeriod.PATH, 'get');
  if (params) {
    rb.path('gameId', params.gameId, {});
    rb.path('userId', params.userId, {});
    rb.path('period', params.period, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GameLeaderboardDto>;
    })
  );
}

getLeaderBoardByGameUserPeriod.PATH = '/gametracker/v1/leaderboard/game/{gameId}/user/{userId}/period/{period}';
