/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameLeaderboardDto } from '../../models/game-leaderboard-dto';

export interface GetLeaderboardEntriesForUserAndGame$Params {
  userId: number;
  gameId: number;
}

export function getLeaderboardEntriesForUserAndGame(http: HttpClient, rootUrl: string, params: GetLeaderboardEntriesForUserAndGame$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GameLeaderboardDto>>> {
  const rb = new RequestBuilder(rootUrl, getLeaderboardEntriesForUserAndGame.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.path('gameId', params.gameId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GameLeaderboardDto>>;
    })
  );
}

getLeaderboardEntriesForUserAndGame.PATH = '/gametracker/v1/leaderboard/user/{userId}/game/{gameId}';
