/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameLeaderboardDto } from '../../models/game-leaderboard-dto';

export interface UpdateScore$Params {
  entryId: number;
  newScore: number;
}

export function updateScore(http: HttpClient, rootUrl: string, params: UpdateScore$Params, context?: HttpContext): Observable<StrictHttpResponse<GameLeaderboardDto>> {
  const rb = new RequestBuilder(rootUrl, updateScore.PATH, 'put');
  if (params) {
    rb.path('entryId', params.entryId, {});
    rb.path('newScore', params.newScore, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GameLeaderboardDto>;
    })
  );
}

updateScore.PATH = '/gametracker/v1/leaderboard/update/{entryId}/{newScore}';
