/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageUserSanctionDto } from '../../models/page-user-sanction-dto';

export interface GetSanctionsHistory$Params {
  userId: number;
  pageable: Pageable;
}

export function getSanctionsHistory(http: HttpClient, rootUrl: string, params: GetSanctionsHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<PageUserSanctionDto>> {
  const rb = new RequestBuilder(rootUrl, getSanctionsHistory.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageUserSanctionDto>;
    })
  );
}

getSanctionsHistory.PATH = '/gametracker/v1/sanctions/history/{userId}';
