/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserSanctionDto } from '../../models/user-sanction-dto';

export interface UpdateSanction$Params {
  sanctionId: number;
      body: UserSanctionDto
}

export function updateSanction(http: HttpClient, rootUrl: string, params: UpdateSanction$Params, context?: HttpContext): Observable<StrictHttpResponse<UserSanctionDto>> {
  const rb = new RequestBuilder(rootUrl, updateSanction.PATH, 'put');
  if (params) {
    rb.path('sanctionId', params.sanctionId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserSanctionDto>;
    })
  );
}

updateSanction.PATH = '/gametracker/v1/sanctions/update/{sanctionId}';
