/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AvatarDto } from '../../models/avatar-dto';

export interface GetAvatarById$Params {
  idAvatar: number;
}

export function getAvatarById(http: HttpClient, rootUrl: string, params: GetAvatarById$Params, context?: HttpContext): Observable<StrictHttpResponse<AvatarDto>> {
  const rb = new RequestBuilder(rootUrl, getAvatarById.PATH, 'get');
  if (params) {
    rb.path('idAvatar', params.idAvatar, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AvatarDto>;
    })
  );
}

getAvatarById.PATH = '/gametracker/v1/avatars/{idAvatar}';
