/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AvatarDto } from '../../models/avatar-dto';

export interface UpdateAvatar1$Params {
  idAvatar: number;
      body: AvatarDto
}

export function updateAvatar1(http: HttpClient, rootUrl: string, params: UpdateAvatar1$Params, context?: HttpContext): Observable<StrictHttpResponse<AvatarDto>> {
  const rb = new RequestBuilder(rootUrl, updateAvatar1.PATH, 'put');
  if (params) {
    rb.path('idAvatar', params.idAvatar, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AvatarDto>;
    })
  );
}

updateAvatar1.PATH = '/gametracker/v1/avatars/update/{idAvatar}';
