/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AvatarDto } from '../../models/avatar-dto';

export interface UploadAvatar$Params {
  multipartFile: Blob;
}

export function uploadAvatar(http: HttpClient, rootUrl: string, params: UploadAvatar$Params, context?: HttpContext): Observable<StrictHttpResponse<AvatarDto>> {
  const rb = new RequestBuilder(rootUrl, uploadAvatar.PATH, 'post');
  if (params) {
    rb.query('multipartFile', params.multipartFile, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AvatarDto>;
    })
  );
}

uploadAvatar.PATH = '/gametracker/v1/avatars/create';
