/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NgModule, ModuleWithProviders, SkipSelf, Optional } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { ApiConfiguration, ApiConfigurationParams } from './api-configuration';

import { UserControllerService } from './services/user-controller.service';
import { TagControllerService } from './services/tag-controller.service';
import { WinStreakControllerService } from './services/win-streak-controller.service';
import { DailyGameSessionControllerService } from './services/daily-game-session-controller.service';
import { UserSanctionControllerService } from './services/user-sanction-controller.service';
import { ReportControllerService } from './services/report-controller.service';
import { GameRecommendationControllerService } from './services/game-recommendation-controller.service';
import { GameRatingControllerService } from './services/game-rating-controller.service';
import { GameProgressControllerService } from './services/game-progress-controller.service';
import { NotificationControllerService } from './services/notification-controller.service';
import { MessageControllerService } from './services/message-controller.service';
import { GameLeaderboardControllerService } from './services/game-leaderboard-controller.service';
import { GameControllerService } from './services/game-controller.service';
import { FriendshipControllerService } from './services/friendship-controller.service';
import { GameCommentControllerService } from './services/game-comment-controller.service';
import { AvatarApiService } from './services/avatar-api.service';
import { AchievementsService } from './services/achievements.service';
import { UserAchievementControllerService } from './services/user-achievement-controller.service';
import { GameTagControllerService } from './services/game-tag-controller.service';
import { PhotosService } from './services/photos.service';
import { GameCommentLikeControllerService } from './services/game-comment-like-controller.service';
import { FavoriteGameControllerService } from './services/favorite-game-controller.service';
import { AuthenticationControllerService } from './services/authentication-controller.service';
import { SeedControllerService } from './services/seed-controller.service';

/**
 * Module that provides all services and configuration.
 */
@NgModule({
  imports: [],
  exports: [],
  declarations: [],
  providers: [
    UserControllerService,
    TagControllerService,
    WinStreakControllerService,
    DailyGameSessionControllerService,
    UserSanctionControllerService,
    ReportControllerService,
    GameRecommendationControllerService,
    GameRatingControllerService,
    GameProgressControllerService,
    NotificationControllerService,
    MessageControllerService,
    GameLeaderboardControllerService,
    GameControllerService,
    FriendshipControllerService,
    GameCommentControllerService,
    AvatarApiService,
    AchievementsService,
    UserAchievementControllerService,
    GameTagControllerService,
    PhotosService,
    GameCommentLikeControllerService,
    FavoriteGameControllerService,
    AuthenticationControllerService,
    SeedControllerService,
    ApiConfiguration
  ],
})
export class ApiModule {
  static forRoot(params: ApiConfigurationParams): ModuleWithProviders<ApiModule> {
    return {
      ngModule: ApiModule,
      providers: [
        {
          provide: ApiConfiguration,
          useValue: params
        }
      ]
    }
  }

  constructor( 
    @Optional() @SkipSelf() parentModule: ApiModule,
    @Optional() http: HttpClient
  ) {
    if (parentModule) {
      throw new Error('ApiModule is already loaded. Import in your base AppModule only.');
    }
    if (!http) {
      throw new Error('You need to import the HttpClientModule in your AppModule! \n' +
      'See also https://github.com/angular/angular/issues/20575');
    }
  }
}
