/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameRatingDto } from '../../models/game-rating-dto';

export interface GetRatingByDate$Params {
  date: string;
}

export function getRatingByDate(http: HttpClient, rootUrl: string, params: GetRatingByDate$Params, context?: HttpContext): Observable<StrictHttpResponse<GameRatingDto>> {
  const rb = new RequestBuilder(rootUrl, getRatingByDate.PATH, 'get');
  if (params) {
    rb.path('date', params.date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GameRatingDto>;
    })
  );
}

getRatingByDate.PATH = '/gametracker/v1/rating/date/{date}';
