/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameRatingDto } from '../../models/game-rating-dto';

export interface GetUserRatingForGame$Params {
  userId: number;
  gameId: number;
}

export function getUserRatingForGame(http: HttpClient, rootUrl: string, params: GetUserRatingForGame$Params, context?: HttpContext): Observable<StrictHttpResponse<GameRatingDto>> {
  const rb = new RequestBuilder(rootUrl, getUserRatingForGame.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.path('gameId', params.gameId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GameRatingDto>;
    })
  );
}

getUserRatingForGame.PATH = '/gametracker/v1/rating/user/{userId}/game/{gameId}';
