/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameRatingDto } from '../../models/game-rating-dto';

export interface UpdateRating$Params {
  ratingId: number;
      body: number
}

export function updateRating(http: HttpClient, rootUrl: string, params: UpdateRating$Params, context?: HttpContext): Observable<StrictHttpResponse<GameRatingDto>> {
  const rb = new RequestBuilder(rootUrl, updateRating.PATH, 'put');
  if (params) {
    rb.path('ratingId', params.ratingId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GameRatingDto>;
    })
  );
}

updateRating.PATH = '/gametracker/v1/rating/{ratingId}/update';
