/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserAchievementDto } from '../../models/user-achievement-dto';

export interface GetUserAchievementById$Params {
  userAchievementId: number;
}

export function getUserAchievementById(http: HttpClient, rootUrl: string, params: GetUserAchievementById$Params, context?: HttpContext): Observable<StrictHttpResponse<UserAchievementDto>> {
  const rb = new RequestBuilder(rootUrl, getUserAchievementById.PATH, 'get');
  if (params) {
    rb.path('userAchievementId', params.userAchievementId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserAchievementDto>;
    })
  );
}

getUserAchievementById.PATH = '/gametracker/v1/userAchievements/{userAchievementId}';
