/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface HasAllPrerequisites$Params {
  userId: number;
  achievementId: number;
}

export function hasAllPrerequisites(http: HttpClient, rootUrl: string, params: HasAllPrerequisites$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new RequestBuilder(rootUrl, hasAllPrerequisites.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.path('achievementId', params.achievementId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

hasAllPrerequisites.PATH = '/gametracker/v1/userAchievements/prerequisites/{userId}/{achievementId}';
