/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FavoriteGameDto } from '../../models/favorite-game-dto';

export interface FindFavoriteByUserAndGame$Params {
  userId: number;
  gameId: number;
}

export function findFavoriteByUserAndGame(http: HttpClient, rootUrl: string, params: FindFavoriteByUserAndGame$Params, context?: HttpContext): Observable<StrictHttpResponse<FavoriteGameDto>> {
  const rb = new RequestBuilder(rootUrl, findFavoriteByUserAndGame.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.path('gameId', params.gameId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FavoriteGameDto>;
    })
  );
}

findFavoriteByUserAndGame.PATH = '/gametracker/v1/favorites/find/{userId}/{gameId}';
