/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameDto } from '../../models/game-dto';

export interface GetFavoriteGamesForUser$Params {
  userId: number;
}

export function getFavoriteGamesForUser(http: HttpClient, rootUrl: string, params: GetFavoriteGamesForUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GameDto>>> {
  const rb = new RequestBuilder(rootUrl, getFavoriteGamesForUser.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GameDto>>;
    })
  );
}

getFavoriteGamesForUser.PATH = '/gametracker/v1/favorites/user/{userId}';
