/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FavoriteGameDto } from '../../models/favorite-game-dto';

export interface GetRecentlyAddedFavoritesForUser$Params {
  userId: number;
}

export function getRecentlyAddedFavoritesForUser(http: HttpClient, rootUrl: string, params: GetRecentlyAddedFavoritesForUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FavoriteGameDto>>> {
  const rb = new RequestBuilder(rootUrl, getRecentlyAddedFavoritesForUser.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FavoriteGameDto>>;
    })
  );
}

getRecentlyAddedFavoritesForUser.PATH = '/gametracker/v1/favorites/recent/{userId}';
