/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FavoriteGameDto } from '../../models/favorite-game-dto';

export interface GetFavoriteById$Params {
  favoriteId: number;
}

export function getFavoriteById(http: HttpClient, rootUrl: string, params: GetFavoriteById$Params, context?: HttpContext): Observable<StrictHttpResponse<FavoriteGameDto>> {
  const rb = new RequestBuilder(rootUrl, getFavoriteById.PATH, 'get');
  if (params) {
    rb.path('favoriteId', params.favoriteId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FavoriteGameDto>;
    })
  );
}

getFavoriteById.PATH = '/gametracker/v1/favorites/{favoriteId}';
