/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Avatar {
  id?: number;
  photo?: string;
  users?: Array<User>;
}
