/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Game } from '../models/game';
import { User } from '../models/user';
export interface GameRecommendation {
  game?: Game;
  id?: number;
  message?: string;
  receiver?: User;
  sender?: User;
}
