/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TagDto } from '../models/tag-dto';
export interface GameTagDto {
  id?: number;
  tag?: TagDto;
}
