/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Game } from '../models/game';
import { GameCommentLike } from '../models/game-comment-like';
import { User } from '../models/user';
export interface GameComment {
  content?: string;
  game?: Game;
  id?: number;
  likes?: Array<GameCommentLike>;
  parentComment?: GameComment;
  replies?: Array<GameComment>;
  user?: User;
}
