/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Game } from '../models/game';
import { Tag } from '../models/tag';
export interface GameTag {
  game?: Game;
  id?: number;
  tag?: Tag;
}
