/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { UserDto } from '../models/user-dto';
export interface GameCommentLikeDto {
  id?: number;
  user?: UserDto;
}
