/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Game } from '../models/game';
import { User } from '../models/user';
export interface GameProgress {
  attempts?: number;
  bestScore?: number;
  currentStreak?: number;
  game?: Game;
  id?: number;
  lastPlayed?: string;
  losses?: number;
  progressData?: string;
  score?: number;
  status?: 'IN_PROGRESS' | 'COMPLETED';
  timePlayed?: number;
  user?: User;
  wins?: number;
}
