/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GameCommentLikeDto } from '../models/game-comment-like-dto';
import { UserDto } from '../models/user-dto';
export interface GameCommentDto {
  content?: string;
  creationDate?: string;
  id?: number;
  lastModifiedDate?: string;
  likes?: Array<GameCommentLikeDto>;
  user?: UserDto;
}
