/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GameComment } from '../models/game-comment';
import { User } from '../models/user';
export interface GameCommentLike {
  comment?: GameComment;
  id?: number;
  user?: User;
}
