/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Message {
  content?: string;
  id?: number;
  isRead?: boolean;
  receiver?: User;
  sender?: User;
}
