/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationDto {
  content?: string;
  creationDate?: string;
  id?: number;
  isRead?: boolean;
  type?: 'FRIEND_REQUEST' | 'MESSAGE' | 'GAME_RECOMMENDATION' | 'ACHIEVEMENT_UNLOCKED' | 'COMMENT_REPLY' | 'COMMENT_LIKE';
}
