/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Notification {
  content?: string;
  id?: number;
  isRead?: boolean;
  type?: 'FRIEND_REQUEST' | 'MESSAGE' | 'GAME_RECOMMENDATION' | 'ACHIEVEMENT_UNLOCKED' | 'COMMENT_REPLY' | 'COMMENT_LIKE';
  user?: User;
}
