/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface Report {
  contentId?: number;
  id?: number;
  reason?: string;
  reported?: User;
  reporter?: User;
  resolvedAt?: string;
  resolver?: User;
  status?: 'PENDING' | 'RESOLVED' | 'DISMISSED';
  type?: 'GAME' | 'COMMENT' | 'MESSAGE';
}
