/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GameTag } from '../models/game-tag';
export interface Tag {
  gameTags?: Array<GameTag>;
  id?: number;
  name?: string;
}
