/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { User } from '../models/user';
export interface UserSanction {
  admin?: User;
  endDate?: string;
  id?: number;
  reason?: string;
  startDate?: string;
  type?: 'WARNING' | 'TEMPORARY_BAN' | 'PERMANENT_BAN';
  user?: User;
}
