/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Achievement } from '../models/achievement';
import { User } from '../models/user';
export interface UserAchievement {
  achievement?: Achievement;
  id?: number;
  unlockedAt?: string;
  user?: User;
}
