/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Avatar } from '../models/avatar';
import { DailyGameSession } from '../models/daily-game-session';
import { FavoriteGame } from '../models/favorite-game';
import { Friendship } from '../models/friendship';
import { GameComment } from '../models/game-comment';
import { GameCommentLike } from '../models/game-comment-like';
import { GameLeaderboard } from '../models/game-leaderboard';
import { GameProgress } from '../models/game-progress';
import { GameRating } from '../models/game-rating';
import { GameRecommendation } from '../models/game-recommendation';
import { Message } from '../models/message';
import { Notification } from '../models/notification';
import { Report } from '../models/report';
import { UserAchievement } from '../models/user-achievement';
import { UserSanction } from '../models/user-sanction';
import { WinStreak } from '../models/win-streak';
export interface User {
  achievementsEarned?: Array<UserAchievement>;
  avatar?: Avatar;
  birthDate?: string;
  comments?: Array<GameComment>;
  country?: string;
  dailyGameSessions?: Array<DailyGameSession>;
  email?: string;
  favoriteGames?: Array<FavoriteGame>;
  friendShipsInitiated?: Array<Friendship>;
  friendshipsReceived?: Array<Friendship>;
  id?: number;
  isActive?: boolean;
  isAdmin?: boolean;
  lastLogin?: string;
  leaderboardsLines?: Array<GameLeaderboard>;
  likes?: Array<GameCommentLike>;
  messagesReceived?: Array<Message>;
  messagesSent?: Array<Message>;
  notifications?: Array<Notification>;
  onlineStatus?: 'ONLINE' | 'OFFLINE' | 'BUSY';
  password?: string;
  points?: number;
  privacySetting?: 'PUBLIC' | 'PRIVATE' | 'FRIENDS_ONLY';
  progressions?: Array<GameProgress>;
  ratings?: Array<GameRating>;
  recommendationsReceived?: Array<GameRecommendation>;
  recommendationsSent?: Array<GameRecommendation>;
  reportsAgainst?: Array<Report>;
  reportsResolved?: Array<Report>;
  reportsSent?: Array<Report>;
  sanctionsDistributed?: Array<UserSanction>;
  sanctionsReceived?: Array<UserSanction>;
  themePreference?: 'LIGHT' | 'DARK';
  totalGamesPlayed?: number;
  totalPlayTime?: number;
  userRank?: 'BRONZE' | 'SILVER' | 'GOLD' | 'MONSTER';
  username?: string;
  winStreaks?: Array<WinStreak>;
}
