/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Game } from '../models/game';
import { User } from '../models/user';
export interface WinStreak {
  bestStreak?: number;
  currentStreak?: number;
  game?: Game;
  id?: number;
  lastWin?: string;
  user?: User;
}
