/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { seedGames } from '../fn/seed-controller/seed-games';
import { SeedGames$Params } from '../fn/seed-controller/seed-games';

@Injectable({ providedIn: 'root' })
export class SeedControllerService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `seedGames()` */
  static readonly SeedGamesPath = '/admin/seed/games';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `seedGames()` instead.
   *
   * This method doesn't expect any request body.
   */
  seedGames$Response(params?: SeedGames$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return seedGames(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `seedGames$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  seedGames(params?: SeedGames$Params, context?: HttpContext): Observable<string> {
    return this.seedGames$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
