/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameCommentDto } from '../../models/game-comment-dto';

export interface AddReplyToComment$Params {
  parentCommentId: number;
      body: GameCommentDto
}

export function addReplyToComment(http: HttpClient, rootUrl: string, params: AddReplyToComment$Params, context?: HttpContext): Observable<StrictHttpResponse<GameCommentDto>> {
  const rb = new RequestBuilder(rootUrl, addReplyToComment.PATH, 'post');
  if (params) {
    rb.path('parentCommentId', params.parentCommentId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GameCommentDto>;
    })
  );
}

addReplyToComment.PATH = '/gametracker/v1/comments/reply/{parentCommentId}';
