/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageGameCommentDto } from '../../models/page-game-comment-dto';

export interface GetCommentReplies$Params {
  parentCommentId: number;
  pageable: Pageable;
}

export function getCommentReplies(http: HttpClient, rootUrl: string, params: GetCommentReplies$Params, context?: HttpContext): Observable<StrictHttpResponse<PageGameCommentDto>> {
  const rb = new RequestBuilder(rootUrl, getCommentReplies.PATH, 'get');
  if (params) {
    rb.path('parentCommentId', params.parentCommentId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageGameCommentDto>;
    })
  );
}

getCommentReplies.PATH = '/gametracker/v1/comments/replies/{parentCommentId}';
