/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameCommentLikeDto } from '../../models/game-comment-like-dto';

export interface AddCommentLike$Params {
  userId: number;
  commentId: number;
}

export function addCommentLike(http: HttpClient, rootUrl: string, params: AddCommentLike$Params, context?: HttpContext): Observable<StrictHttpResponse<GameCommentLikeDto>> {
  const rb = new RequestBuilder(rootUrl, addCommentLike.PATH, 'post');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.path('commentId', params.commentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GameCommentLikeDto>;
    })
  );
}

addCommentLike.PATH = '/gametracker/v1/game-comment-likes/toggle/{userId}/{commentId}';
