/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameCommentLikeDto } from '../../models/game-comment-like-dto';

export interface GetLikeById$Params {
  likeId: number;
}

export function getLikeById(http: HttpClient, rootUrl: string, params: GetLikeById$Params, context?: HttpContext): Observable<StrictHttpResponse<GameCommentLikeDto>> {
  const rb = new RequestBuilder(rootUrl, getLikeById.PATH, 'get');
  if (params) {
    rb.path('likeId', params.likeId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GameCommentLikeDto>;
    })
  );
}

getLikeById.PATH = '/gametracker/v1/game-comment-likes/{likeId}';
