/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageGameCommentLikeDto } from '../../models/page-game-comment-like-dto';

export interface GetAllLikes$Params {
  pageable: Pageable;
}

export function getAllLikes(http: HttpClient, rootUrl: string, params: GetAllLikes$Params, context?: HttpContext): Observable<StrictHttpResponse<PageGameCommentLikeDto>> {
  const rb = new RequestBuilder(rootUrl, getAllLikes.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageGameCommentLikeDto>;
    })
  );
}

getAllLikes.PATH = '/gametracker/v1/game-comment-likes/admin/all';
