/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageNotificationDto } from '../../models/page-notification-dto';

export interface GetNotificationHistory$Params {
  userId: number;
  pageable: Pageable;
      body: {
'startDate'?: string;
'endDate'?: string;
}
}

export function getNotificationHistory(http: HttpClient, rootUrl: string, params: GetNotificationHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<PageNotificationDto>> {
  const rb = new RequestBuilder(rootUrl, getNotificationHistory.PATH, 'get');
  if (params) {
    rb.path('userId', params.userId, {});
    rb.query('pageable', params.pageable, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageNotificationDto>;
    })
  );
}

getNotificationHistory.PATH = '/gametracker/v1/notification/user/{userId}/history';
