/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameTagDto } from '../../models/game-tag-dto';

export interface AddTagToGame$Params {
  gameId: number;
  tagId: number;
}

export function addTagToGame(http: HttpClient, rootUrl: string, params: AddTagToGame$Params, context?: HttpContext): Observable<StrictHttpResponse<GameTagDto>> {
  const rb = new RequestBuilder(rootUrl, addTagToGame.PATH, 'post');
  if (params) {
    rb.path('gameId', params.gameId, {});
    rb.path('tagId', params.tagId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GameTagDto>;
    })
  );
}

addTagToGame.PATH = '/gametracker/v1/game/{gameId}/tag/{tagId}';
