/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameTagDto } from '../../models/game-tag-dto';
import { Pageable } from '../../models/pageable';

export interface GetMostPopularTags$Params {
  pageable: Pageable;
}

export function getMostPopularTags(http: HttpClient, rootUrl: string, params: GetMostPopularTags$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GameTagDto>>> {
  const rb = new RequestBuilder(rootUrl, getMostPopularTags.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GameTagDto>>;
    })
  );
}

getMostPopularTags.PATH = '/gametracker/v1/tags/popular';
