/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageGameTagDto } from '../../models/page-game-tag-dto';

export interface GetGamesForTag$Params {
  tagId: number;
  pageable: Pageable;
}

export function getGamesForTag(http: HttpClient, rootUrl: string, params: GetGamesForTag$Params, context?: HttpContext): Observable<StrictHttpResponse<PageGameTagDto>> {
  const rb = new RequestBuilder(rootUrl, getGamesForTag.PATH, 'get');
  if (params) {
    rb.path('tagId', params.tagId, {});
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageGameTagDto>;
    })
  );
}

getGamesForTag.PATH = '/gametracker/v1/tag/{tagId}/games';
