/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GameTagDto } from '../../models/game-tag-dto';

export interface UpdateTagAssociation$Params {
  associationId: number;
      body: number
}

export function updateTagAssociation(http: HttpClient, rootUrl: string, params: UpdateTagAssociation$Params, context?: HttpContext): Observable<StrictHttpResponse<GameTagDto>> {
  const rb = new RequestBuilder(rootUrl, updateTagAssociation.PATH, 'post');
  if (params) {
    rb.path('associationId', params.associationId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GameTagDto>;
    })
  );
}

updateTagAssociation.PATH = '/gametracker/v1/tag/{associationId}/update';
