/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Pageable } from '../../models/pageable';
import { PageTagDto } from '../../models/page-tag-dto';

export interface GetAllTags$Params {
  pageable: Pageable;
}

export function getAllTags(http: HttpClient, rootUrl: string, params: GetAllTags$Params, context?: HttpContext): Observable<StrictHttpResponse<PageTagDto>> {
  const rb = new RequestBuilder(rootUrl, getAllTags.PATH, 'get');
  if (params) {
    rb.query('pageable', params.pageable, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageTagDto>;
    })
  );
}

getAllTags.PATH = '/gametracker/v1/tags/all';
